include: package:flutter_lints/flutter.yaml

linter:
  rules:
    public_member_api_docs: true
    package_api_docs: true
    prefer_const_constructors: true
    avoid_renaming_method_parameters: true
    avoid_unused_constructor_parameters: true
    avoid_types_as_parameter_names: true
    avoid_empty_else: true
